script:
- echo "Starting build..."
before_deploy:
    - git config --local user.name "torresashjian"
    - git config --local user.email "migueltorreslopez@gmail.com"
    - export PRERELEASE=$(make is-prerelease BUILD_BRANCH=${TRAVIS_BRANCH})
    - export RELEASE_NOTES=$(make release-notes)
    - export VERSION_TAG=$(make tag BUILD_BRANCH=${TRAVIS_BRANCH} BUILD_NUM=${TRAVIS_BUILD_NUMBER})
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(${VERSION_TAG})}
    - make hyperledger-fabric-artifacts BUILD_TAG=${TRAVIS_TAG}
    - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: .target/hyperledger-fabric/*
  skip_cleanup: true
  prerelease: $PRERELEASE
  name: $TRAVIS_TAG
  body: "$RELEASE_NOTES"
  on:
    branch:
    - master
    - develop