kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: orderer-data-class
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
# create one PV for each orderer instance
metadata:
  name: data-orderer-0
  labels:
    node: orderer-0
    org: netop1
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orderer-data-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bcd6c917
    volumeAttributes:
      path: /data/orderer-0
---
kind: PersistentVolume
apiVersion: v1
# create one PV for each orderer instance
metadata:
  name: data-orderer-1
  labels:
    node: orderer-1
    org: netop1
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orderer-data-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bcd6c917
    volumeAttributes:
      path: /data/orderer-1
---
kind: PersistentVolume
apiVersion: v1
# create one PV for each orderer instance
metadata:
  name: data-orderer-2
  labels:
    node: orderer-2
    org: netop1
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orderer-data-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bcd6c917
    volumeAttributes:
      path: /data/orderer-2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-orderer-0
  namespace: netop1
spec:
  storageClassName: orderer-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      node: orderer-0
      org: netop1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-orderer-1
  namespace: netop1
spec:
  storageClassName: orderer-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      node: orderer-1
      org: netop1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-orderer-2
  namespace: netop1
spec:
  storageClassName: orderer-data-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      node: orderer-2
      org: netop1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bcd6c917
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer
  namespace: netop1
spec:
  selector:
    matchLabels:
      app: orderer
  serviceName: orderer
  replicas: 3
  template:
    metadata:
      labels:
        app: orderer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: linux
        image: amazonlinux:2 
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /efs-data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: data
          mountPath: /efs-data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: "orderer-data-class"
      resources:
        requests:
          storage: 500Mi
---
kind: Service
apiVersion: v1
metadata:
  name: orderer
  namespace: netop1
  labels:
    app: orderer
spec:
  selector:
    app: orderer
  ports:
  - port: 7050
    name: server
  # headless service for orderer StatefulSet
  clusterIP: None
